### ISSUE TITLE
Add GitHub workflow for release build

### ISSUE THREAD

**Issue by krazkidd** [krazkidd/kdeck#19]
We can automatically build to provide a download option through GitHub.

This should use a Docker container and any build options should be made available through whatever solution is provided for #18.

Only a Linux build is required at this time.

> [!IMPORTANT]
> **We must be careful to comply with any licensing requirements of any packaged dependencies.**

**Comment by krazkidd** [comment]
Copilot offered a Docker-based Workflow build:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-cpp-project .

    - name: Run Build in Docker Container
      run: docker run -v "$(pwd):/src" my-cpp-project make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./build/output
```
